mods.jei.JEI.hide(<mekanism:oreblock:1>);
mods.jei.JEI.hide(<mekanism:robit:*>);
mods.jei.JEI.hide(<mekanism:machineblock:15>);
mods.jei.JEI.hide(<mekanism:transmitter:0>.withTag({tier: 0}));
mods.jei.JEI.hide(<mekanism:transmitter:0>.withTag({tier: 1}));
mods.jei.JEI.hide(<mekanism:transmitter:0>.withTag({tier: 2}));
mods.jei.JEI.hide(<mekanism:transmitter:0>.withTag({tier: 3}));
mods.jei.JEI.hide(<mekanism:energycube:0>.withTag({tier: 4}));
mods.jei.JEI.hide(<mekanismgenerators:reactor:0>);
mods.jei.JEI.hide(<mekanismgenerators:reactor:1>);
mods.jei.JEI.hide(<mekanismgenerators:reactor:2>);
mods.jei.JEI.hide(<mekanismgenerators:reactor:3>);
mods.jei.JEI.hide(<mekanismgenerators:reactorglass:0>);
mods.jei.JEI.hide(<mekanismgenerators:reactorglass:1>);
mods.jei.JEI.hide(<tconstruct:pickaxe>);
mods.jei.JEI.hide(<tconstruct:shovel>);
mods.jei.JEI.hide(<tconstruct:hatchet>);
mods.jei.JEI.hide(<tconstruct:mattock>);
mods.jei.JEI.hide(<tconstruct:hammer>);
mods.jei.JEI.hide(<tconstruct:excavator>);
mods.jei.JEI.hide(<tconstruct:lumberaxe>);
mods.jei.JEI.hide(<tconstruct:scythe>);
mods.jei.JEI.hide(<tconstruct:broadsword>);
mods.jei.JEI.hide(<tconstruct:longsword>);
mods.jei.JEI.hide(<tconstruct:rapier>);
mods.jei.JEI.hide(<tconstruct:frypan>);
mods.jei.JEI.hide(<tconstruct:battlesign>);
mods.jei.JEI.hide(<tconstruct:cleaver>);
mods.jei.JEI.hide(<tconstruct:shortbow>);
mods.jei.JEI.hide(<tconstruct:longbow>);
mods.jei.JEI.hide(<tconstruct:crossbow>);
mods.jei.JEI.hide(<tconstruct:arrow>);
mods.jei.JEI.hide(<tconstruct:bolt>);
mods.jei.JEI.hide(<tconstruct:shuriken>);
mods.jei.JEI.hide(<chisel:ironpane:1>);
mods.jei.JEI.hide(<chisel:ironpane:2>);
mods.jei.JEI.hide(<chisel:ironpane:3>);
mods.jei.JEI.hide(<chisel:ironpane:5>);
mods.jei.JEI.hide(<chisel:ironpane:6>);
mods.jei.JEI.hide(<chisel:ironpane:7>);
mods.jei.JEI.hide(<chisel:ironpane:8>);
mods.jei.JEI.hide(<chisel:testblock>);
mods.jei.JEI.hide(<forestry:resources:1>);
mods.jei.JEI.hide(<forestry:resources:2>);
mods.jei.JEI.hide(<forestry:resource_storage:1>);
mods.jei.JEI.hide(<forestry:resource_storage:2>);
mods.jei.JEI.hide(<forestry:ingot_copper>);
mods.jei.JEI.hide(<forestry:ingot_tin>);
mods.jei.JEI.hide(<harvestcraft:beehive>);
mods.jei.JEI.hide(<harvestcraft:pamapple>);
mods.jei.JEI.hide(<rftools:coalgenerator>);
mods.jei.JEI.hide(<rftools:invisible_shield_block>);
mods.jei.JEI.hide(<rftools:notick_invisible_shield_block>);
mods.jei.JEI.hide(<rftools:solid_shield_block>);
mods.jei.JEI.hide(<rftools:notick_solid_shield_block>);
mods.jei.JEI.hide(<immersiveengineering:metal:0>);
mods.jei.JEI.hide(<immersiveengineering:metal:8>);
mods.jei.JEI.hide(<immersiveengineering:metal:17>);
mods.jei.JEI.hide(<immersiveengineering:storage:0>);
mods.jei.JEI.hide(<immersiveengineering:storage:8>);
mods.jei.JEI.hide(<immersiveengineering:storage_slab:0>);
mods.jei.JEI.hide(<immersiveengineering:storage_slab:8>);
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_overclock"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_culinary"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_death"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_enchant"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_ender"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_tnt"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_ice"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_dragonsbreath"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_redstone"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_lava"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_netherstar"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_pink"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_potion"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_slime"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_survival"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:furnace"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:crusher"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_explosive"}));
mods.jei.JEI.hide(<extrautils2:machine:0>.withTag({Type: "extrautils2:generator_dischantment"}));
mods.jei.JEI.hide(<extrautils2:machine:0>);
mods.jei.JEI.hide(<extrautils2:supermobspawner>);
